// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'bootstrap', 'serializeObject'], function(Chaplin) {
  'use strict';
  var Application;
  return Application = (function(_super) {
    __extends(Application, _super);

    function Application() {
      return Application.__super__.constructor.apply(this, arguments);
    }

    Application.prototype.title = 'Where To Go?';

    Application.prototype.initRouter = function(routes, options) {
      if (options == null) {
        options = {};
      }
      options.pushState = false;
      return Application.__super__.initRouter.call(this, routes, options);
    };

    return Application;

  })(Chaplin.Application);
});
