// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['singleton', 'async!http://maps.google.com/maps/api/js?sensor=true&key=AIzaSyAU43H9HS_S0p94SLnuU-oxadj6tzdUXx0'], function(Singleton) {
  'use strict';
  var Geo;
  return Geo = (function(_super) {
    __extends(Geo, _super);

    function Geo() {
      this.getCoordsError = __bind(this.getCoordsError, this);
      this.getCoords = __bind(this.getCoords, this);
      return Geo.__super__.constructor.apply(this, arguments);
    }

    Geo.prototype.firstCoords = {
      lat: 46.48048,
      lng: 30.756235
    };

    Geo.prototype.init = function() {
      this.geocoder = new google.maps.Geocoder();
      return this.getCoords((function(_this) {
        return function(position) {
          _this.firstCoords.lat = position.coords.latitude;
          return _this.firstCoords.lng = position.coords.longitude;
        };
      })(this));
    };

    Geo.prototype.getCoords = function(callback, errorback) {
      if (errorback == null) {
        errorback = this.getCoordsError;
      }
      if (navigator.geolocation) {
        return navigator.geolocation.getCurrentPosition(callback, errorback);
      } else {
        return errorback(1);
      }
    };

    Geo.prototype.getCoordsError = function(error) {
      switch (error.code) {
        case error.PERMISSION_DENIED:
          return alert("User denied the request for Geolocation.");
        case error.POSITION_UNAVAILABLE:
          return alert("Location information is unavailable.");
        case error.TIMEOUT:
          return alert("The request to get user location timed out.");
        case error.UNKNOWN_ERROR:
          return alert("An unknown error occurred.");
      }
    };

    return Geo;

  })(Singleton);
});
