// Generated by CoffeeScript 1.7.1
define(function() {
  'use strict';
  return function(match) {
    match('', 'main#index');
    match('login', 'user#login');
    match('logout', 'user#logout');
    match('profile', 'user#edit');
    match('settings', 'user#edit');
    match('new', 'events#add');
    return match('event/:id', 'events#show');
  };
});

//# sourceMappingURL=routes.map
