// Generated by CoffeeScript 1.7.1
define(function() {
  'use strict';
  var Singleton;
  return Singleton = (function() {
    var instance;

    function Singleton() {}

    instance = null;

    Singleton.get = function() {
      if (this.instance == null) {
        instance = new this;
        instance.init();
      }
      return instance;
    };

    Singleton.prototype.init = function(name) {
      if (name == null) {
        name = "unknown";
      }
      return console.log("" + name + " initialized");
    };

    return Singleton;

  })();
});

//# sourceMappingURL=singleton.map
