// Generated by CoffeeScript 1.7.1
define(function() {
  'use strict';
  var Singleton;
  return Singleton = (function() {
    var instance;

    function Singleton() {}

    instance = void 0;

    Singleton.get = function() {
      return instance != null ? instance : instance = new this;
    };

    return Singleton;

  })();
});
