// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'views/site-view', 'views/header-view'], function(Chaplin, SiteView, HeaderView) {
  'use strict';
  var Controller;
  return Controller = (function(_super) {
    __extends(Controller, _super);

    function Controller() {
      return Controller.__super__.constructor.apply(this, arguments);
    }

    Controller.prototype.beforeAction = function() {
      this.reuse('site', SiteView);
      return this.reuse('header', HeaderView, {
        region: 'header'
      });
    };

    return Controller;

  })(Chaplin.Controller);
});
