// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'text!templates/user/edit.hbs'], (function(_this) {
  return function(View, template) {
    'use strict';
    var SiteView;
    return SiteView = (function(_super) {
      __extends(SiteView, _super);

      function SiteView() {
        _this.initialize = __bind(_this.initialize, this);
        return SiteView.__super__.constructor.apply(this, arguments);
      }

      SiteView.prototype.container = 'body';

      SiteView.prototype.template = template;

      template = null;

      SiteView.prototype.autoRender = true;

      SiteView.prototype.initialize = function(model) {
        SiteView.__super__.initialize.apply(this, arguments);
        return console.log(model);
      };

      return SiteView;

    })(View);
  };
})(this));

//# sourceMappingURL=edit.map
