// Generated by CoffeeScript 1.7.1
define(['underscore', 'chaplin'], function(_, Chaplin) {
  'use strict';
  var utils;
  utils = Chaplin.utils.beget(Chaplin.utils);
  return utils;
});

//# sourceMappingURL=utils.map
