// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'text!templates/main/index.hbs', 'geo'], function(View, template, Geo) {
  'use strict';
  var IndexView;
  return IndexView = (function(_super) {
    __extends(IndexView, _super);

    function IndexView() {
      this.addMarker = __bind(this.addMarker, this);
      this.setCenter = __bind(this.setCenter, this);
      this.createMap = __bind(this.createMap, this);
      this.initialize = __bind(this.initialize, this);
      return IndexView.__super__.constructor.apply(this, arguments);
    }

    IndexView.prototype.autoRender = true;

    IndexView.prototype.region = 'main';

    IndexView.prototype.template = template;

    template = null;

    IndexView.prototype.initialize = function() {
      IndexView.__super__.initialize.apply(this, arguments);
      return this.geo = Geo.get();
    };

    IndexView.prototype.attach = function() {
      IndexView.__super__.attach.apply(this, arguments);
      this.createMap(new google.maps.LatLng(this.geo.firstCoords.lat, this.geo.firstCoords.lng));
      return this.geo.getCoords((function(_this) {
        return function(position) {
          var latlng;
          latlng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
          return _this.map.setCenter(latlng);
        };
      })(this));
    };

    IndexView.prototype.createMap = function(startCoords) {
      var mapOptions;
      mapOptions = {
        zoom: 14,
        center: startCoords,
        mapTypeControl: true,
        mapTypeControlOptions: {
          style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
        },
        navigationControl: true,
        navigationControlOptions: {
          style: google.maps.NavigationControlStyle.SMALL
        },
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      this.map = new google.maps.Map(this.$el.find("#mapView")[0], mapOptions);
      return this.me = new google.maps.Marker({
        position: startCoords,
        map: this.map,
        title: "You are here!"
      });
    };

    IndexView.prototype.setCenter = function(LatLng) {
      this.map.setCenter(LatLng);
      return this.me.setPosition(LatLng);
    };

    IndexView.prototype.addMarker = function(LatLng) {};

    return IndexView;

  })(View);
});
